eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8003
spring:
  application:
    name: lcy-server

feign:
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true